### ISSUE TITLE
Non-static vs Static

### ISSUE THREAD

**Issue by richerimage** [voidzone/thesis_developer_asset_handler#1]
Hi Tim

I'm getting the following:

Strict Standards: Non-static method thesis_skins::get_items() should not be called statically in /var/www/vhosts/boxmythesis.com/httpdocs/wp-content/thesis/boxes/sweet_tweet/assets/dna_asset_handler.php on line 33

(this gets repeated for boxes and packages too ) 

Would I be causing this error somehow?

Thanks Tim

**Comment by voidzone** [comment]
Woah, sorry for the abhorrent turn around on this, didn't get a notification about the issue.

Did you find a fix for it?

From what I'm reading it sounds like the fix would be to hack the Thesis core and re-declare those methods as public static rather than just public, but that sounds like an awful idea.

**Comment by richerimage** [comment]
No probs Tim - Rick (byob) has a working version 'sans-hacking' - I'll get it over to you

**Comment by voidzone** [comment]
Hmmm he's probably still running v1.3. I'll take a look.

**Comment by voidzone** [comment]
Weird, can't reproduce the issue even with E_ALL under php 5.5.16.

What version of php were you getting it with?
